version: '3.8'

services:
  url-redirect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - .:/app
    command: go run cmd/main.go
