# Build stage
FROM golang:1.24 AS builder

WORKDIR /workers

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o workers ./cmd/workers

# Production stage
FROM alpine:3.20

RUN apk --no-cache add ca-certificates

WORKDIR /workers

COPY --from=builder /workers/workers .

RUN adduser -D -g '' appuser
USER appuser

ENTRYPOINT ["./workers"]
