services:
  url-redirect:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - REDIRECT_PERFORMED_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:redirect_performed_topic
      - REDIRECT_PERFOMED_COUNTER_UPDATE_QUEUE_URL=http://sqs.us-east-1.localhost:4566/000000000000/redirect_performed_counter_update_queue
      - REDIRECT_PERFORMED_METRICS_QUEUE_URL=http://sqs.us-east-1.localhost:4566/000000000000/redirect_performed_metrics_queue
    volumes:
      - .:/app
    command: go run cmd/server/main.go

  localstack:
    image: localstack/localstack:4.3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sqs,sns
      - DEBUG=1
      - LOCALSTACK_HOST=localhost
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./init-scripts:/etc/localstack/init/ready.d"
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
