// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IDB is an autogenerated mock type for the IDB type
type IDB struct {
	mock.Mock
}

type IDB_Expecter struct {
	mock *mock.Mock
}

func (_m *IDB) EXPECT() *IDB_Expecter {
	return &IDB_Expecter{mock: &_m.Mock}
}

// GetItem provides a mock function with given fields: _a0, Id
func (_m *IDB) GetItem(_a0 context.Context, Id string) (map[string]any, error) {
	ret := _m.Called(_a0, Id)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 map[string]any
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]any, error)); ok {
		return rf(_a0, Id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]any); ok {
		r0 = rf(_a0, Id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, Id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IDB_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type IDB_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - _a0 context.Context
//   - Id string
func (_e *IDB_Expecter) GetItem(_a0 interface{}, Id interface{}) *IDB_GetItem_Call {
	return &IDB_GetItem_Call{Call: _e.mock.On("GetItem", _a0, Id)}
}

func (_c *IDB_GetItem_Call) Run(run func(_a0 context.Context, Id string)) *IDB_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IDB_GetItem_Call) Return(_a0 map[string]any, _a1 error) *IDB_GetItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IDB_GetItem_Call) RunAndReturn(run func(context.Context, string) (map[string]any, error)) *IDB_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewIDB creates a new instance of IDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDB {
	mock := &IDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
