// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/pedropazello/url-redirect-service/entities"

	mock "github.com/stretchr/testify/mock"
)

// IRedirectPerformedNotificator is an autogenerated mock type for the IRedirectPerformedNotificator type
type IRedirectPerformedNotificator struct {
	mock.Mock
}

type IRedirectPerformedNotificator_Expecter struct {
	mock *mock.Mock
}

func (_m *IRedirectPerformedNotificator) EXPECT() *IRedirectPerformedNotificator_Expecter {
	return &IRedirectPerformedNotificator_Expecter{mock: &_m.Mock}
}

// Notificate provides a mock function with given fields: _a0, _a1
func (_m *IRedirectPerformedNotificator) Notificate(_a0 context.Context, _a1 entities.Redirect) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Notificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Redirect) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IRedirectPerformedNotificator_Notificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notificate'
type IRedirectPerformedNotificator_Notificate_Call struct {
	*mock.Call
}

// Notificate is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 entities.Redirect
func (_e *IRedirectPerformedNotificator_Expecter) Notificate(_a0 interface{}, _a1 interface{}) *IRedirectPerformedNotificator_Notificate_Call {
	return &IRedirectPerformedNotificator_Notificate_Call{Call: _e.mock.On("Notificate", _a0, _a1)}
}

func (_c *IRedirectPerformedNotificator_Notificate_Call) Run(run func(_a0 context.Context, _a1 entities.Redirect)) *IRedirectPerformedNotificator_Notificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Redirect))
	})
	return _c
}

func (_c *IRedirectPerformedNotificator_Notificate_Call) Return(_a0 error) *IRedirectPerformedNotificator_Notificate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRedirectPerformedNotificator_Notificate_Call) RunAndReturn(run func(context.Context, entities.Redirect) error) *IRedirectPerformedNotificator_Notificate_Call {
	_c.Call.Return(run)
	return _c
}

// NewIRedirectPerformedNotificator creates a new instance of IRedirectPerformedNotificator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRedirectPerformedNotificator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRedirectPerformedNotificator {
	mock := &IRedirectPerformedNotificator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
