// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ITopic is an autogenerated mock type for the ITopic type
type ITopic struct {
	mock.Mock
}

type ITopic_Expecter struct {
	mock *mock.Mock
}

func (_m *ITopic) EXPECT() *ITopic_Expecter {
	return &ITopic_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, msg
func (_m *ITopic) Publish(ctx context.Context, msg string) (string, error) {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, msg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ITopic_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type ITopic_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
func (_e *ITopic_Expecter) Publish(ctx interface{}, msg interface{}) *ITopic_Publish_Call {
	return &ITopic_Publish_Call{Call: _e.mock.On("Publish", ctx, msg)}
}

func (_c *ITopic_Publish_Call) Run(run func(ctx context.Context, msg string)) *ITopic_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ITopic_Publish_Call) Return(_a0 string, _a1 error) *ITopic_Publish_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ITopic_Publish_Call) RunAndReturn(run func(context.Context, string) (string, error)) *ITopic_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewITopic creates a new instance of ITopic. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITopic(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITopic {
	mock := &ITopic{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
